spring:
  application:
    name: bibliotheque

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bibliotheque
    username: esgi
    password: esgi

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    try-it-out-enabled: true
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
